---
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r, echo=F}
pacman::p_load(
  rio,
  here,
  janitor,
  ISOcodes,
  tidyverse,
  googlesheets4,
  reactable
)
```

## Welcome to our Support Desk service!

If you need to talk through an R problem or have your code reviewed by an epidemiology and R expert, this is the place to be. 

For Intro to R course participants: You are entitled to 1.5 hours of support, divided into three 30-minute calls. These calls can be one-on-one with the technician, or you can invite team members from the R course to join. Time is deducted from the booking student, so attending calls in groups means you can get more time.

## Instructions

1) Select a day and time below that works for you. The earliest available time for a review session is 24 hours from time of booking.  
    * **IMPORTANT**: Ensure the timezone reflects your location. If you are in the Philippines, it should be  "China/Singapore/Perth". 
2) Click 'next' and then:
    * Enter your name, email address, and a brief description of the support you need.
    * Include the email addresses of any team or group members who should join the call.
3) A Google Meets calendar invitation will be sent to the provided email address(es).

You can modify or cancel your booking via the calendar invitation as long as it’s done at least 24 hours in advance. Changes made less than 24 hours before the appointment will result in forfeiting the scheduled time.

If there are any specific issues or concerns, please email paula.blomquist@appliedepi.org. 

## Booking form

```{=html}

<!-- Calendly inline widget begin -->
<div class="calendly-inline-widget" data-url="https://calendly.com/support-desk-test/code-review-any-available-instructor?hide_event_type_details=1&hide_gdpr_banner=1" style="min-width:320px;height:700px;"></div>
<script type="text/javascript" src="https://assets.calendly.com/assets/external/widget.js" async></script>
<!-- Calendly inline widget end -->
```


## About us

[**Applied Epi**](https://www.appliedepi.org/) is a nonprofit organisation and grassroots movement of frontline epidemiologists from around the world. Your encouragement and feedback is most welcome:

-   Visit our [**website**](https://www.appliedepi.org/) and [**join our contact list**](https://docs.google.com/forms/d/e/1FAIpQLSdtk7Mg32lYQ3ucbIM-kIwIRxgRwDfG5TJHsVAbFjQ1i6fwiw/viewform?usp=send_form)

-   **contact\@appliedepi.org**, tweet [**\@appliedepi**](https://x.com/appliedepi), or [**LinkedIn**](https://www.linkedin.com/company/appliedepi/?originalSubdomain=it)

-   Submit issues to our **Github repository**